plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
    ignore: "*/Tests/*"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,design,naming,unusedcode"
  phan:
    enabled: true
    config:
      file_extensions: "php"
exclude_patterns:
  - "**/Tests/"
  - "**/vendor/"
