language: php
php:
  - 7.4.4

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
